// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewyiiuhwikfuzraqucka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3eWlpdWh3aWtmdXpyYXF1Y2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzUxNDEsImV4cCI6MjA2MTgxMTE0MX0.NM7WTt0cmcRFRMgP1Nf7cUIS_433zI7l7RNiYgUZ7Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);